#!/bin/sh

""":" # pdfsizeopt3: PDF file size optimizer (Python 3 version)

P="$(readlink "$0" 2>/dev/null)"
test "$P" && test "${P#/}" = "$P" && P="${0%/*}/$P"
test "$P" || P="$0"
type python3 >/dev/null 2>&1 && exec python3 -- "$P" ${1+"$@"}
exec python -- "$P" ${1+"$@"}; exit 1

This is a Python 3 script, it works with Python 3.6 or later. Feel free to
replace the #! line with `#! /usr/bin/env python3' or whatever suits you best.
"""

import os
import os.path
import sys

if sys.version_info[:2] < (3, 6):
  sys.stderr.write('fatal: Python 3.6 or later needed for: %s\n' % __file__)
  sys.exit(1)

script_dir = os.path.dirname(__file__)
try:
  __file__ = os.path.join(script_dir, os.readlink(__file__))
  script_dir = os.path.dirname(__file__)
except (OSError, AttributeError, NotImplementedError):
  pass
if os.path.isfile(os.path.join(
    script_dir, 'lib', 'pdfsizeopt', 'main.py')):
  sys.path[0] = os.path.join(script_dir, 'lib')

from pdfsizeopt import main
sys.exit(main.main(sys.argv, script_dir=script_dir))
